{
 "title": "Mikrotik monitoring",
 "description": "Mikrotik Dashboard",
 "tags": [
  "prometheus",
  "Mikrotik",
  "snmp",
  "snmp v3",
  "snmp_exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(mikrotik_system_uptime,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mikrotik_system_uptime,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mikrotik_system_uptime{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Total hdd space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mikrotik_system_total_hdd_space{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mikrotik_system_total_memory{instance='$instance'}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mikrotik_system_cpu_load{instance='$instance'})"
    }
   ]
  },
  {
   "title": "RAM load ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - (mikrotik_system_free_memory{instance=\"$instance\"} / mikrotik_system_total_memory{instance=\"$instance\"})) * 100\n"
    }
   ]
  },
  {
   "title": "Disk load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - (mikrotik_system_free_hdd_space{instance='$instance'} / mikrotik_system_total_hdd_space{instance='$instance'})) * 100\n"
    }
   ]
  },
  {
   "title": "Board ver",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mikrotik_system_uptime{instance='$instance'}",
     "legendFormat": "{{boardname}} {{version}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "mikrotik_interface_rx_packet", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "description": "Status link/states: The current operational state of the interface",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mikrotik_interface_running{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Tx Eth errors, etc",
   "type": "timeseries",
   "description": "Showing values > 0",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(mikrotik_interface_tx_error{instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Control - {{ifName}}"
    },
    {
     "expr": "irate(mikrotik_interface_tx_drop{instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Control - {{ifName}}"
    }
   ]
  },
  {
   "title": "Rx Eth errors, etc",
   "type": "timeseries",
   "description": "Showing values > 0",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(mikrotik_interface_rx_error{instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Align Error - {{ifName}}"
    },
    {
     "expr": "irate(mikrotik_interface_rx_drop{instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Align Error - {{ifName}}"
    }
   ]
  }
 ]
}